//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt18_praktika_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public Nullable<int> Kol { get; set; }
        public int AgeCategory { get; set; }
        public string FactoryName { get; set; }
        public string CityFactory { get; set; }
    }
}
